services:
  database:
    image: mysql:8.0
    container_name: my-store-db
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_ROOT_PASSWORD: hello1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: my-store-api
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: hello1234
      DB_NAME: log430_db
    ports:
      - "3000:3000"
    command: node server.js
    volumes:
      - .:/app

volumes:
  db_data:
